---
interval: 2
movementDir: "/opt/dragon"
servos:
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "nekturn"
  number: 1
  min: 100
  rest: 300
  max: 500
  currentPosition: 300
  newPosition: 0
  newRandomPosition: 0
- name: "nekleft"
  number: 2
  min: 100
  rest: 300
  max: 500
  currentPosition: 300
  newPosition: 0
  newRandomPosition: 0
- name: "nekright"
  number: 3
  min: 100
  rest: 300
  max: 500
  currentPosition: 300
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
- name: "noname"
  number: 0
  min: 0
  rest: 0
  max: 0
  currentPosition: 0
  newPosition: 0
  newRandomPosition: 0
debug: "INFO"
